version: '3'
services:
  bounded-context-canvas-management:
    build: .
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      mariadb:
        condition: service_started
      bounded-context-canvas:
        condition: service_started
      kroki:
        condition: service_started
  kroki:
    image: docker.io/yuzutech/kroki:0.26.0
    restart: always
    ports:
      - "8085:8000"
  bounded-context-canvas:
    image: docker.io/adam85w/bounded-context-canvas:3.2.1
    restart: unless-stopped
    ports:
      - "8083:8083"
  mariadb:
    image: docker.io/mariadb:11.6-noble
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: letmein1
      MYSQL_DATABASE: canvases
      MYSQL_USER: canvas
      MYSQL_PASSWORD: letmein1
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: docker.io/phpmyadmin:5.2.2-apache
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: canvas
      PMA_PASSWORD: letmein1
    ports:
      - "8082:80"
    depends_on:
      mariadb:
        condition: service_healthy